permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : 万国文化
author :
  name : echozhjun 
  email : echozhjun(at)gmail.com
  github : echozhjun
  twitter : echozhjun
production_url : http://wanguo.github.com

BASE_PATH : 
ASSET_PATH : /assets

comments :
  provider : false
         
analytics : 
  provider : false
sharing :
  provider : false

